-- PHASE 4: PROACTIVE & FUN FEATURES
-- Run this in your Supabase SQL Editor

-- 1. Enhance daily_status table
ALTER TABLE daily_status 
ADD COLUMN IF NOT EXISTS custom_status TEXT,
ADD COLUMN IF NOT EXISTS custom_emoji TEXT;

-- 2. Create kudos table (for fun recognitions)
CREATE TABLE IF NOT EXISTS kudos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  to_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  type TEXT DEFAULT 'star', -- 'star', 'rocket', 'heart', etc.
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable realtime for kudos
ALTER PUBLICATION supabase_realtime ADD TABLE kudos;

-- 4. Enable RLS for kudos
ALTER TABLE kudos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view kudos" 
  ON kudos FOR SELECT 
  USING (true);

CREATE POLICY "Users can give kudos" 
  ON kudos FOR INSERT 
  WITH CHECK (auth.uid() = from_user_id);

-- 5. FUNCTION and TRIGGER for Push Notifications on ALL local notifications
-- This ensures that any "addNotification" (like nudges or automated alerts)
-- automatically sends a push notification to the user.

CREATE OR REPLACE FUNCTION public.notify_push_on_notification_insert()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM net.http_post(
    url := 'https://geaspnqzexuoaarycrsi.supabase.co/functions/v1/send-push',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || 'TU_ANON_KEY_O_SERVICE_ROLE'
    ),
    body := jsonb_build_object(
      'user_id', NEW.user_id,
      'title', 'Aviso de Solaris',
      'message', NEW.message,
      'url', '/notifications'
    )
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_notification_created ON public.notifications;
CREATE TRIGGER on_notification_created
  AFTER INSERT ON public.notifications
  FOR EACH ROW EXECUTE FUNCTION public.notify_push_on_notification_insert();

-- 6. Instructions for Scheduling (pg_cron)
-- If you have the pg_cron extension enabled:
-- SELECT cron.schedule('lunch-reminder', '0 14 * * *', 'SELECT net.http_post(url := ''https://geaspnqzexuoaarycrsi.supabase.co/functions/v1/automated-reminders'', headers := ''{"Authorization": "Bearer TU_SERVICE_ROLE"}''::jsonb)');
