-- Create calendar_events table for global day events
CREATE TABLE IF NOT EXISTS calendar_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_key TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;

-- Policies
-- Everyone can read
CREATE POLICY "Everyone can read calendar events" ON calendar_events
  FOR SELECT USING (true);

-- Authenticated users can insert
CREATE POLICY "Users can create calendar events" ON calendar_events
  FOR INSERT WITH CHECK (auth.uid() = created_by);

-- Users can delete their own events (or admins?)
-- For now, allow creators to delete
CREATE POLICY "Users can delete their own events" ON calendar_events
  FOR DELETE USING (auth.uid() = created_by);

-- Allow admins to delete any event (optional but good practice, assuming admin role check logic exists or we just rely on Supabase dashboard for super admin)
-- Using a simpler policy for now: creators can delete.
